version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./AppVeyorIntegration/AppVeyorIntegration.csproj --verbosity m
build_script:
  # output will be in ./bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./AppVeyorIntegration/AppVeyorIntegration.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\AppVeyorIntegration\bin\Debug\netcoreapp2.1\publish'
   name: AppVeyorIntegration
   type: WebDeployPackage
clone_depth: 1
test_script:
on_finish :
  # any cleanup in here
deploy: off